# Customise this file, documentation can be found here:
# https://github.com/fastlane/fastlane/tree/master/fastlane/docs
# All available actions: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Actions.md
# can also be listed using the `fastlane actions` command

# Change the syntax highlighting to Ruby
# All lines starting with a # are ignored when running `fastlane`

# If you want to automatically update fastlane if a new version is available:
#update_fastlane

# This is the minimum version number required.
# Update this, if you use features of a newer version
fastlane_version "1.97.2"

default_platform :ios

platform :ios do
  before_all do
    # ENV["SLACK_URL"] = "https://hooks.slack.com/services/..."   
  end
  
  desc "Check all certs and provisioning profiles from github"
  lane :checkcerts do
    app_root = "com.irccloud."
    for type in ["appstore", "adhoc", "development"] do
      for app in ["IRCCloud", "enterprise"] do
        match(type: type, app_identifier: "#{app_root}#{app}", readonly: true)
        match(type: type, app_identifier: "#{app_root}#{app}.ShareExtension", readonly: true)
      end
    end
  end

  #desc "Runs all the tests"
  #lane :test do
  #  scan
  #end

  desc "Make sure all devices are added to the ad-hoc profile"
  lane :updateadhoc do
    match(type: "adhoc", force_for_new_devices: true, app_identifier: "com.irccloud.IRCCloud")
    match(type: "adhoc", force_for_new_devices: true, app_identifier: "com.irccloud.IRCCloud.ShareExtension")
  end

  desc "Build and archive an ad-hoc release"
  lane :beta do
    gym(scheme: "IRCCloud", export_method: "ad-hoc", clean: true, configuration: "Release")
  end

  #desc "Deploy a new version to the App Store"
  #lane :appstore do
    # match(type: "appstore")
    # snapshot
    ## gym(scheme: "IRCCloud") # Build your app - more options available
    ## deliver(force: true)
    # frameit
  #end

  # You can define as many lanes as you want

  after_all do |lane|
    # This block is called, only if the executed lane was successful

    # slack(
    #   message: "Successfully deployed new App Update."
    # )
  end

  error do |lane, exception|
    # slack(
    #   message: exception.message,
    #   success: false
    # )
  end
end


# More information about multiple platforms in fastlane: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Platforms.md
# All available actions: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Actions.md

# fastlane reports which actions are used
# No personal data is recorded. Learn more at https://github.com/fastlane/enhancer
#
